chrzaszcz:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: first_to_base
    pid: {p: 20.0, i: 0.01, d: 0.01}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: second_to_first
    pid: {p: 20.0, i: 0.01, d: 0.01}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: third_to_second
    pid: {p: 20.0, i: 0.01, d: 0.01}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: fourth_to_third
    pid: {p: 5.0, i: 0.01, d: 0.01}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: fifth_to_fourth
    pid: {p: 1.0, i: 0.01, d: 0.01}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_gripper_to_fifth_link
    pid: {p: 200.0, i: 0.1, d: 0.001}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_gripper_to_fifth_link
    pid: {p: 200.0, i: 0.1, d: 0.001}
